[package]
name = "scd4x"
version = "0.1.0"
authors = ["Hauke Jung <hauke.jung@outlook.de>"]
documentation = "https://docs.rs/sgp30"
repository = "https://github.com/hauju/scd4x-rs.git"
license = "MIT OR Apache-2.0"
description = "Rust driver for the Sensirion SCD4x series. Carbon Dioxide / Temperature / Humidity sensors."
keywords = ["scd4x", "scd40", "scd41", "sensirion", "driver", "embedded-hal-driver"]
categories = ["embedded", "no-std"]
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sensirion-i2c = "0.1"
embedded-hal = "0.2"

[dev-dependencies]
linux-embedded-hal = "0.3"
embedded-hal-mock = "0.7"
